Generating LALR tables
S> Starting TSDB server on port 9999
Traceback (most recent call last):
  File "//anaconda/envs/py35/lib/python3.5/asyncio/base_events.py", line 905, in create_server
    sock.bind(sa)
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "go_persistent_server.py", line 36, in <module>
    main()
  File "go_persistent_server.py", line 32, in main
    server.run()
  File "/Users/Elena/Desktop/CS207/TimeSeries/tsdb/tsdb_server.py", line 196, in run
    listener = loop.run_until_complete(self.listener)
  File "//anaconda/envs/py35/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "//anaconda/envs/py35/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "//anaconda/envs/py35/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "//anaconda/envs/py35/lib/python3.5/asyncio/base_events.py", line 909, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 9999): address already in use
